# \u670D\u52A1\u5668\u914D\u7F6E
server:
  port: 8090

# \u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    name: druid
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///springbootdata?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

# \u6574\u5408mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # \u58F0\u660EMybatis\u6620\u5C04\u6587\u4EF6\u6240\u5728\u7684\u4F4D\u7F6E
  type-aliases-package: com.lagou.pojo
