server:
  port: 8001
spring:
  application:
    name: test-front
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${sprig.cloud.client.ip-address}:${server.port}