spring:
  datasource:
    url: jdbc:mysql:///mp?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

mybatis-plus:
# 加载全局配置文件
  config-location: classpath:SqlMapConfig.xml
# 加载映射配置文件
  mapper-locations: classpath*:mapper/*.xml
# 起别名
  type-aliases-package: com.lagou.pojo
# 关闭自动驼峰命名映射
  #configuration:
    #map-underscore-to-camel-case: false
  # 设置全局的主键生成策略：自增
  global-config:
    db-config:
      id-type: auto
      # 全局配置表名前缀
      #table-prefix: tb_
      # 告知mp逻辑已删除值（默认为1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为0）
      logic-not-delete-value: 0
