spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdata?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 192.168.114.128 # redis主机地址
    port: 6379            # 端口号
    jedis:
      pool:
        max-active: 18  # 设置连接池的最大连接数
        max-wait: 3000  # 连接池最大阻塞等待时间
        max-idle: 20    # 连接池中最大的空闲连接数
        min-idle: 2     # 连接池中最小的空闲连接数
    timeout: 3000 # 连接的超时时间
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名匹配映射
  mapper-locations: classpath:mapper/*.xml  # 就会resource下的mapper文件夹下的所有mapper文件加载
  type-aliases-package: com.lagou.pojo  # 配置xml映射文件中指定的实体类别名的扫描路径
